variables:
  MAVEN_OPTS: "-Xms256m -Xmx256m -XX:+UseSerialGC"

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test_job:
  stage: test
  script:
    - mvn test
  dependencies:
    - build_job
